(define (has-devisor? n k) 
  (cond ((< k 2) #false)
        ((= (modulo n k) 0) #true)
        (else (has-devisor? n (- k 1)))
  )
)

(define (has-devisor-2? n k)
  (define (div? n d)
       (and (> d 0) (= (remainder n d) 0))
  )
  (cond ((< k 2) #false)
        ((= (modulo n k) 0) #true)
        (else (has-devisor? n (- k 1)))
  )
)
 
(define (prime? n)
  (not (has-devisor? n (ceiling (sqrt n))))
)
  
(define (prime-2? n)
  (not (has-devisor-2? n (ceiling (sqrt n))))
)